# Generated by Django 5.0.6 on 2024-05-08 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        ('patron', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_borrowed', models.DateTimeField()),
                ('date_due', models.DateTimeField()),
                ('date_returned', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='book.book')),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='patron.patron')),
            ],
        ),
    ]
