# Generated by Django 5.0.6 on 2024-05-09 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_id_alter_transaction_is_returned'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date_borrowed']},
        ),
    ]
