# Generated by Django 5.0.6 on 2024-05-09 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_book_copies_on_loan'),
        ('transaction', '0007_alter_transaction_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='book.book'),
        ),
    ]
