# Generated by Django 5.0.6 on 2024-05-08 03:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('book_cover', models.ImageField(blank=True, default='default_images/default_book_cover.png', null=True, upload_to='book_covers/')),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=200, unique=True)),
                ('publisher', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('available_copies', models.IntegerField()),
                ('pending_returns', models.IntegerField(blank=True, default=0, editable=False, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
