# Generated by Django 5.0.6 on 2024-05-08 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pending_returns',
            new_name='copies_on_loan',
        ),
    ]
