# Generated by Django 5.0.6 on 2024-05-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_copies_on_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='copies_on_loan',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
