# Generated by Django 5.0.6 on 2024-05-09 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0003_alter_patron_pending_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='pending_return',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
