# Generated by Django 5.0.6 on 2024-05-09 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0004_alter_patron_pending_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='patron',
            name='late_returns',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
