# Generated by Django 5.0.6 on 2024-05-09 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0005_patron_late_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='late_returns',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
