# Generated by Django 5.0.6 on 2024-05-09 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patron', '0006_alter_patron_late_returns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patron',
            name='late_returns',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
